services:

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}

  
  db:
    image: postgres:18
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

    backend:
      restart: on-failure
      build:
        context: backend
      volumes:
        - ./backend:/app
        - /app/node_modules
      ports:
        - ${BACKEND_PORT}

      frontend:
        restart: on-failure
        build:
          context: frontend
        volumes:
          - ./frontend:/app
          - /app/node_modules
        ports:
          - ${FRONTEND_PORT}


